server:
  port: 8000
spring:
  application:
    name: zuul-server

zuul:
  routes:
    member:
      path: /member-service/**
      url: http://localhost:8081
    eureka-client:
      path: /eureka-client/**
      url: http://localhost:8888
    order:
      path: /order-service/**
      url: http://localhost:8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka